services:
  lb:
    image: ghcr.io/thales-maciel/zordon:latest
    entrypoint: ["/app/zordon-lb"]
    environment:
      LB_PORT: "9999"
      LB_BACKENDS: "/sock/api1.sock,/sock/api2.sock"
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sock
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "24MB"

  api1:
    image: ghcr.io/thales-maciel/zordon:latest
    environment:
      ZORDON_MODEL_PATH: "/app/model/references.i16.bin"
      ZORDON_UNIX_PATH: "/sock/api1.sock"
      ZORDON_MAX_CANDIDATES: "30000"
    volumes:
      - sockets:/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "163MB"

  api2:
    image: ghcr.io/thales-maciel/zordon:latest
    environment:
      ZORDON_MODEL_PATH: "/app/model/references.i16.bin"
      ZORDON_UNIX_PATH: "/sock/api2.sock"
      ZORDON_MAX_CANDIDATES: "30000"
    volumes:
      - sockets:/sock
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "163MB"

volumes:
  sockets:
